# Generated by Django 4.2 on 2023-04-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='commented_photos',
            field=models.ManyToManyField(related_name='user_comments', to='picture.photo', verbose_name='Прокомментированные фото'),
        ),
        migrations.AddField(
            model_name='account',
            name='favorites',
            field=models.ManyToManyField(related_name='user_favorites', to='picture.photo', verbose_name='Избранное'),
        ),
    ]
